 # processing.minmaxscaler

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = [[-1,2],[-0.5,6],[0,10],[1,18]]

In [5]:
data

[[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [6]:
import pandas as pd
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [7]:
#实现归一化
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result = scaler.transform(data)

In [8]:
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [9]:
result_ = scaler.fit_transform(data)

In [10]:
scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [11]:
# 使用MinMaxScaler 的参数feature_range实现将数据归一化到[0,1]以外的范围中
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
scaler = MinMaxScaler(feature_range=[5,10])
scaler.fit_transform(data)

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [12]:
#使用numpy来实现归一化
import numpy as np
x = np.array([[-1,2],[-0.5,6],[0,10],[1,18]])
#归一化
x_nor = (x - x.min(axis=0)/(x.max(axis=0) - x.min(axis=0)))
x_nor

array([[-0.5  ,  1.875],
       [ 0.   ,  5.875],
       [ 0.5  ,  9.875],
       [ 1.5  , 17.875]])

In [13]:
#逆转归一化
x_returned =x_nor *(x.max(axis=0) - x.min(axis=0)) + x.min(axis=0)

In [14]:
x_returned

array([[ -2.,  32.],
       [ -1.,  96.],
       [  0., 160.],
       [  2., 288.]])

# preprocessng.StandardScaler

In [15]:
# x1 = (x-均值)/标准差

In [19]:
from sklearn.preprocessing import StandardScaler
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
ss = StandardScaler()
x_std = ss.fit_transform(data)

In [17]:
ss.mean_

array([-0.125,  9.   ])

In [18]:
ss.var_

array([ 0.546875, 35.      ])

In [20]:
x_std.mean()
x_std.std()

1.0

In [21]:
ss.inverse_transform(x_std)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

# 2.2 缺失值

In [25]:
import pandas as pd
data = pd.read_csv('./Narrativedata.csv',index_col=0)# 第0列作为索引

In [30]:
data.head()

count       mean        std   min     25%   50%   75%   max
Age  714.0  29.699118  14.526497  0.42  20.125  28.0  38.0  80.0

In [34]:
data.count(axis =0)/len(data)

Age         0.801347
Sex         1.000000
Embarked    0.997755
Survived    1.000000
dtype: float64

# impute.SimpleImputer

In [46]:
Age = data.loc[:,'Age'].values.reshape(-1,1)#sklearn中特征矩阵必须是二维

In [55]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer()
imp_median = SimpleImputer(strategy='median')
imp_0 = SimpleImputer(strategy='constant',fill_value=0)

In [56]:
imp_mean = imp_mean.fit_transform(Age)
imp_median = imp_median.fit_transform(Age)
imp_0 = imp_0.fit_transform(Age)

In [57]:
data.loc[:,'Age'] = imp_median

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [59]:
#使用众数填补embarked
Embarked = data.loc[:,'Embarked'].values.reshape(-1,1)

In [60]:
imp_mode = SimpleImputer(strategy = 'most_frequent')
data.loc[:,'Embarked'] = imp_mode.fit_transform(Embarked)
data.info()


<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  891 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [61]:
import pandas as pd
data = pd.read_csv('./Narrativedata.csv',index_col=0)# 第0列作为索引

data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [62]:
data.loc[:,'Age'] = data.loc[:,'Age'].fillna(data.loc[:,'Age'].median())

In [63]:
data.dropna(axis=0,inplace=True)

# 2.3 处理分类型特征：编码与哑变量

# preprocessing.LabelEncoder 标签专用，能够将分类转换为数值

In [65]:
from sklearn.preprocessing import LabelEncoder
y = data.iloc[:,-1]
le = LabelEncoder()
le = le.fit(y)
label = le.transform(y)

le.classes_
label

le.fit_transform(y)

le.inverse_transform(label)


array(['No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'Unknown', 'Yes', 'No', 'No', 'No', 'Unknown', 'No', 'Yes', 'No',
       'Yes', 'Unknown', 'Yes', 'Yes', 'Yes', 'No', 'Unknown', 'No', 'No',
       'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'Unknown', 'Yes', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'Yes', 'Unknown', 'No', 'Unknown',
       'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Unknown', 'Yes',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'No', 'Unknown', 'No', 'No', 'Yes', 'No', 'No', 'Ye

In [68]:
label

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2,
       0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0, 0,
       2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0, 1,
       0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 2,
       0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1, 0,
       0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2,
       0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2,

# preprocessing.OrdinalEncoder:特征专用，能够将分类特征转换为分类数值

In [70]:
from sklearn.preprocessing import OrdinalEncoder
data_ = data.copy()
data_.head()
OrdinalEncoder().fit(data_.iloc[:,1:-1]).categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [71]:
data.iloc[:,1:-1] = OrdinalEncoder().fit_transform(data_.iloc[:,1:-1])

data_.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

# preprocessing.OneHotEncoder :独热编码，创建哑变量

In [72]:
data.head()

Age  Sex Embarked Survived
0  22.0  1.0      2.0       No
1  38.0  0.0      0.0      Yes
2  26.0  0.0      2.0      Yes
3  35.0  0.0      2.0      Yes
4  35.0  1.0      2.0       No

In [ ]:
from sklearn.preprocessing import OneHotEncoder
x = data.loc[:,1:-1]
enc = OneHotEncoder(categories='auto').fit(x)
result = enc.transform